name: VPN CI

on:
  push:
    branches: [ "master", "develop" ] 
  pull_request:
    branches: [ "master" ]         

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen --all-packages

      - name: Run tests
        run: uv run pytest
        env:
          SERVER_IP: "127.0.0.1"
          SERVER_PORT: "8080"
          PRIVATE_KEY_PATH: "tests/keys/private_key.pem"
          PUBLIC_KEY_PATH: "tests/keys/public_key.pem"
          SERVER_PUBLIC_KEY: "tests/keys/server_private_key.pem"
          
